'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MainNoForm

    '''<summary>
    '''HeadContentPlaceHolderMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContentPlaceHolderMain As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''LeftPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeftPane As Global.DevExpress.Web.ASPxPanel

    '''<summary>
    '''ASPxNavBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxNavBar1 As Global.DevExpress.Web.ASPxNavBar

    '''<summary>
    '''ASPxSiteMapDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxSiteMapDataSource1 As Global.DevExpress.Web.ASPxSiteMapDataSource

    '''<summary>
    '''MainContentPlaceHolderMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContentPlaceHolderMain As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
