'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cadastro

    '''<summary>
    '''btnExcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcluir As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnDesistir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDesistir As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnSair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSair As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControl1 As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''ASPxFormLayout0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout0 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''cmbPesqTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPesqTipo As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtPesqCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesqCodigo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''btnPesquisar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPesquisar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnImprimir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImprimir As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cmbPesqPFPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPesqPFPJ As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtPesqNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesqNome As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''gridCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCadastro As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''dsCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCadastro As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''lbCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCodigo As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''rbPFPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPFPJ As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''gridCadastroTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCadastroTipo As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''dsCadastroTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCadastroTipo As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''txtNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtCPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPF As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''rbSexo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSexo As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''txtDataNascimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataNascimento As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''txtRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRG As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtIEPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIEPF As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtEmailPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailPF As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelFixoPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelFixoPF As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelCelularPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelCelularPF As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelAltPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelAltPF As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelFaxPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelFaxPF As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtRazaoSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRazaoSocial As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtNomeFantasia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeFantasia As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtCNPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNPJ As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtIEPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIEPJ As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtEmailPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailPJ As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelFixoPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelFixoPJ As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelCelularPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelCelularPJ As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelAltPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelAltPJ As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtTelFaxPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelFaxPJ As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout2 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtLogradouro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogradouro As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtNumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumero As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtComplemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComplemento As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBairro As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmbCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCidade As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtCEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCEP As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtLogradouroAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogradouroAux As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtNumeroAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroAux As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtComplementoAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComplementoAux As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtBairroAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBairroAux As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cmbCidadeAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCidadeAux As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtCEPAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCEPAux As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout3 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtLoginUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoginUsuario As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''gridRolesUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridRolesUsuario As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''dsRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRoles As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''txtSenhaUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSenhaUsuario As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtSenhaConfirmarUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSenhaConfirmarUsuario As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''chkHabilitadoUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHabilitadoUsuario As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''ASPxValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxValidationSummary1 As Global.DevExpress.Web.ASPxValidationSummary

    '''<summary>
    '''litMsgGenerica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMsgGenerica As Global.System.Web.UI.WebControls.Literal
End Class
