/* CodeFluent Generated . TargetVersion:Sql2014. Culture:en-US. UiCulture:en-US. Encoding:utf-8 (http://www.softfluent.com) */
set quoted_identifier OFF
GO
DECLARE @rv rowversion
DECLARE @su nvarchar(64)
SELECT @su=SYSTEM_USER
EXECUTE [dbo].[apprelatorio_Save] @pId=1, @pNomeFormArgumento=N'FormArgRelProduto', @pNomeRelatorio=N'RelProduto', @pNomeRdlc=N'S5TWin.RelProduto.rdlc', @pNomeDataSet=N'dsProduto', @sCategoria=3, @pTituloRelatorio=N'RELACAO DE PRODUTOS', @pSequencia=10, @pCategoriaRelatorio=N'Estoque', @_trackLastWriteUser=@su
EXECUTE [dbo].[apprelatorio_Save] @pId=2, @pNomeFormArgumento=N'FormArgRelProduto', @pNomeRelatorio=N'RelProdutoGrupo', @pNomeRdlc=N'S5TWin.RelProdutoGrupo.rdlc', @pNomeDataSet=N'dsProduto', @sCategoria=3, @pTituloRelatorio=N'RELACAO DE PRODUTOS POR GRUPO', @pSequencia=20, @pCategoriaRelatorio=N'Estoque', @_trackLastWriteUser=@su
EXECUTE [dbo].[apprelatorio_Save] @pId=3, @pNomeFormArgumento=N'FormArgRelProduto', @pNomeRelatorio=N'RelProdutoGrupo2', @pNomeRdlc=N'S5TWin.RelProdutoGrupo.rdlc', @pNomeDataSet=N'dsProduto', @sCategoria=2, @pTituloRelatorio=N'RELACAO DE PRODUTOS POR GRUPO CONTABIL', @pSequencia=30, @pCategoriaRelatorio=N'Contabilidade', @_trackLastWriteUser=@su
EXECUTE [dbo].[apprelatorio_Save] @pId=4, @pNomeFormArgumento=N'FormArgRelTitulo', @pNomeRelatorio=N'RelTituloSintetico', @pNomeRdlc=N'S5TWin.RelTituloSintetico.rdlc', @pNomeDataSet=N'DataSetTitulo', @sCategoria=4, @pTituloRelatorio=N'RELACAO SINTETICA DE TITULOS', @pSequencia=40, @pCategoriaRelatorio=N'Financeiro', @_trackLastWriteUser=@su
EXECUTE [dbo].[apprelatorio_Save] @pId=5, @pNomeFormArgumento=N'FormArgRelTitulo', @pNomeRelatorio=N'RelTituloAnalitico', @pNomeRdlc=N'S5TWin.RelTituloAnalitico.rdlc', @pNomeDataSet=N'DataSetTitulo', @sCategoria=4, @pTituloRelatorio=N'RELACAO ANALITICA DE TITULOS', @pSequencia=50, @pCategoriaRelatorio=N'Financeiro', @_trackLastWriteUser=@su
EXECUTE [dbo].[apprelatorio_Save] @pId=6, @pNomeFormArgumento=N'FormArgRelRecibo', @pNomeRelatorio=N'RelRecibo', @pNomeRdlc=N'S5TWin', @pNomeDataSet=N'ds', @sCategoria=6, @pTituloRelatorio=N'RECIBO FECHAMENTO', @pSequencia=60, @pCategoriaRelatorio=N'Fechamento Mensal', @_trackLastWriteUser=@su
EXECUTE [dbo].[apprelatorio_Save] @pId=7, @pNomeFormArgumento=N'FormArgRelServico', @pNomeRelatorio=N'RelServico', @pNomeRdlc=N'RelDxServico', @pNomeDataSet=N'ds', @sCategoria=7, @pTituloRelatorio=N'RELATORIO DE SERVICO', @pSequencia=70, @pCategoriaRelatorio=N'Servico', @_trackLastWriteUser=@su
EXECUTE [dbo].[cadastro_Save] @pId=1, @pNome=N'RENATO XAVIER', @pCodigo=1, @pPFPJ=N'F', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.AZARIAS M.QUEIROZ', @pEnderComplemento=default, @pEnderBairro=N'PARAISO DO BOSQUE', @pEnderNumero=N'660', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=N'renatoferreiraxavier@gmail.com', @oCidadeAux_pId=default, @pCpfCnpj=N'950.048.906-68', @pDataNascimento='19720413 00:00:00.000', @pRgIe=N'M4041476', @pNomeFantasia=default, @pFlgSexo=N'M', @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[cadastrotipo_Savecadastroocadastrostipo] @pId=1, @pId2=1
EXECUTE [dbo].[cadastrotipo_Savecadastroocadastrostipo] @pId=1, @pId2=2
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=1, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=2, @pNome=N'RAPHAEL BRIGAGAO', @pCodigo=2, @pPFPJ=N'F', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.DOS LAGOS', @pEnderComplemento=default, @pEnderBairro=N'SUMARE', @pEnderNumero=N'442', @pEnderAuxLogradouro=default, @pEnderAuxNumero=N'', @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=default, @oCidadeAux_pId=default, @pCpfCnpj=N'733.789.221-76', @pDataNascimento='19871016 00:00:00.000', @pRgIe=N'2977269', @pNomeFantasia=default, @pFlgSexo=N'M', @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'16252-231', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=2, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=3, @pNome=N'ANDERSON COLOMBAROLI', @pCodigo=3, @pPFPJ=N'F', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.EUROPA', @pEnderComplemento=default, @pEnderBairro=N'JARDIM EUROPA', @pEnderNumero=N'201', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=N'anderson@4tsistemas.com.br', @oCidadeAux_pId=default, @pCpfCnpj=N'421.344.889-48', @pDataNascimento='19770516 00:00:00.000', @pRgIe=N'429434121', @pNomeFantasia=default, @pFlgSexo=N'M', @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=3, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=4, @pNome=N'SANDRO SILVEIRA', @pCodigo=4, @pPFPJ=N'F', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.FORMOSA', @pEnderComplemento=default, @pEnderBairro=N'VILA FORMOSA', @pEnderNumero=N'48', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=N'sandro@4tsistemas.com.br', @oCidadeAux_pId=default, @pCpfCnpj=N'216.642.612-30', @pDataNascimento='19760310 00:00:00.000', @pRgIe=N'418757896', @pNomeFantasia=default, @pFlgSexo=N'M', @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=4, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=5, @pNome=N'LUIZ GUILHERME MARQUES', @pCodigo=5, @pPFPJ=N'F', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.PAINEIRAS', @pEnderComplemento=default, @pEnderBairro=N'JARDIM DAS PAINEIRAS', @pEnderNumero=N'102', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=default, @oCidadeAux_pId=default, @pCpfCnpj=N'330.258.454-73', @pDataNascimento='19821230 00:00:00.000', @pRgIe=N'403289440', @pNomeFantasia=default, @pFlgSexo=N'M', @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=5, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=6, @pNome=N'ANDREY VOLTE A SORRIR', @pCodigo=6, @pPFPJ=N'F', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.AMADOR BUENO', @pEnderComplemento=default, @pEnderBairro=N'CENTRO', @pEnderNumero=N'58', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=default, @oCidadeAux_pId=default, @pCpfCnpj=N'584.080.455-04', @pDataNascimento='19801112 00:00:00.000', @pRgIe=N'403289440', @pNomeFantasia=default, @pFlgSexo=N'M', @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=6, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=7, @pNome=N'CARLOS EDUARDO DE OLIVEIRA', @pCodigo=7, @pPFPJ=N'F', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.BERNARDETE', @pEnderComplemento=default, @pEnderBairro=N'JARDIM BERNARDETE', @pEnderNumero=N'211', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=default, @oCidadeAux_pId=default, @pCpfCnpj=N'433.721.519-09', @pDataNascimento='19790512 00:00:00.000', @pRgIe=N'418757896', @pNomeFantasia=default, @pFlgSexo=N'M', @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=7, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=8, @pNome=N'MATRIZ DA EMPRESA', @pCodigo=8, @pPFPJ=N'J', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.JOANA', @pEnderComplemento=default, @pEnderBairro=N'CENTRO', @pEnderNumero=N'312', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=default, @oCidadeAux_pId=default, @pCpfCnpj=N'02.789.432/0001-59', @pDataNascimento='19800812 00:00:00.000', @pRgIe=N'6479889640020', @pNomeFantasia=default, @pFlgSexo=default, @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=8, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=9, @pNome=N'FILIAL 1 DA EMPRESA', @pCodigo=9, @pPFPJ=N'J', @pEndereco=default, @oCidade_pId=1, @pEnderLogradouro=N'R.MARQUES', @pEnderComplemento=default, @pEnderBairro=N'CENTRO', @pEnderNumero=N'553', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=default, @oCidadeAux_pId=default, @pCpfCnpj=N'02.789.432/0001-59', @pDataNascimento='19851015 00:00:00.000', @pRgIe=N'6479889640020', @pNomeFantasia=default, @pFlgSexo=default, @pDataCadastro=default, @pDataBaixa=default, @pTelefone=default, @pTelefoneAux=default, @pCelular=default, @pFax=default, @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=9, @pId2=1
EXECUTE [dbo].[cadastro_Save] @pId=10, @pNome=N'ASSOC. COM. IND. AGROP. E DE SERV. DE S.S. PARAISO', @pCodigo=10, @pPFPJ=N'J', @pEndereco=N'AV. OLIVEIRA RESENDE, 1.350', @oCidade_pId=1, @pEnderLogradouro=N'AV. OLIVEIRA RESENDE', @pEnderComplemento=default, @pEnderBairro=N'BRAS', @pEnderNumero=N'1.350', @pEnderAuxLogradouro=default, @pEnderAuxNumero=default, @pEnderAuxBairro=default, @pEnderAuxComplemento=default, @pEnderecoAux=default, @pEmail=default, @oCidadeAux_pId=default, @pCpfCnpj=N'19.829.498/0001-28', @pDataNascimento=default, @pRgIe=default, @pNomeFantasia=N'ACISSP', @pFlgSexo=default, @pDataCadastro=default, @pDataBaixa=default, @pTelefone=N'(35)3539-4400', @pTelefoneAux=default, @pCelular=default, @pFax=N'(35)3539-4407', @xDataHoraReg=default, @xLoginReg=N'ADMIN', @oUsuario_pId=default, @pCep=N'37950-000', @pCepAux=default, @pFlgPreCadastro=default, @oCadastroFilial_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Savecadastrooempresas] @pId=10, @pId2=1
EXECUTE [dbo].[cadastrotipo_Save] @pId=1, @pDescricao=N'USUARIO', @pFlgCadastro=N'USU', @xDataHoraReg=default, @xLoginReg=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[cidade_Save] @pId=1, @pNome=N'SAO SEBASTIAO DO PARAISO', @pCodigo=1, @pCodigoIbge=3164704, @oUF_pId=1, @xDataHoraReg=default, @xLoginReg=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[empresa_Save] @pId=1, @pCodigo=1, @pNome=N'4T SISTEMAS LTDA', @xDataHoraReg=default, @xLoginReg=default, @pSimplesNacionalValorAliquotaCreditoICMS=3, @sSimplesNacionalCategoria=1, @sCodigoRegimeTributario=1, @sCodigoRegimeTributarioNormal=0, @_trackLastWriteUser=@su
EXECUTE [dbo].[filial_Save] @pId=1, @pCodigo=1, @pNome=N'MATRIZ', @sTipo=1, @xDataHoraReg=default, @xLoginReg=default, @oEmpresa_pId=1, @oCadastro_pId=10, @_trackLastWriteUser=@su
EXECUTE [dbo].[filial_Save] @pId=2, @pCodigo=2, @pNome=N'FILIAL 1', @sTipo=2, @xDataHoraReg=default, @xLoginReg=default, @oEmpresa_pId=1, @oCadastro_pId=9, @_trackLastWriteUser=@su
EXECUTE [dbo].[filialconfig_Save] @pId=1, @sTipo=1, @pConteudo=N'1', @xDataHoraReg=default, @xLoginReg=default, @oFilial_pId=1, @_trackLastWriteUser=@su
EXECUTE [dbo].[filialconfig_Save] @pId=2, @sTipo=1, @pConteudo=N'1', @xDataHoraReg=default, @xLoginReg=default, @oFilial_pId=2, @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=1, @Name=N'AdmMaster', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdUser_SaveIdRoleUsers] @Id=1, @Id2=1
EXECUTE [dbo].[IdRole_Save] @Id=2, @Name=N'Admin BI4T', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=3, @Name=N'Cenario Colheita de Cana', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=4, @Name=N'Entrada de Cana', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=5, @Name=N'Entrada de Cana Mapa', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=6, @Name=N'Entrada de Cana por Origem', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=7, @Name=N'Entrada de Cana por Propriedade', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=8, @Name=N'Mapa de Entrada por Propriedade', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=9, @Name=N'Pivot Entrada de Cana', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=10, @Name=N'Relatorio Entradas por Propriedade', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=11, @Name=N'Cenario Oficina Automotiva', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=12, @Name=N'Resumo Oficina', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=13, @Name=N'Detalhamento Oficina', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=14, @Name=N'Cenario Entrada Cana Mobile', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=15, @Name=N'Moagem de Cana Hora', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdRole_Save] @Id=16, @Name=N'Certificado de Cana Hora', @_trackLastWriteUser=@su
EXECUTE [dbo].[IdUser_Save] @Id=1, @UserName=N'admin@4t.com.br', @CreationDateUTC='20141223 13:20:27.000', @Email=N'admin@4t.com.br', @EmailConfirmed=0, @PhoneNumber=default, @PhoneNumberConfirmed=0, @Password=N'AIu7vPIjWA0rCXMB6qtwRCWX/8nIzMPqyAgpKZdfzx2gkY7MfYCezR5QyXG8BHxSvA==', @LastPasswordChangeDate='20141223 13:20:26.000', @AccessFailedCount=0, @AccessFailedWindowStart=default, @LockoutEnabled=1, @LockoutEndDateUtc=default, @LastProfileUpdateDate=default, @SecurityStamp=N'bf31cefa-3766-4472-ac59-ffd5fb0b3b5f', @TwoFactorEnabled=0, @oUsuario_pId=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[pais_Save] @pId=1, @pCodigo=1, @pNome=N'BRASIL', @pSigla=N'BRA', @pCodigoIbge=1058, @xDataHoraReg=default, @xLoginReg=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[sistema_Save] @pId=1, @pNome=N'SISTEMA INTEGRADO DE GESTAO EMPRESARIAL', @pCodigo=1, @xDataHoraReg=default, @xLoginReg=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[sistema_Saveempresaosistemas] @pId=1, @pId2=1
EXECUTE [dbo].[uf_Save] @pId=1, @pCodigo=1, @pDescricao=N'MINAS GERAIS', @pSigla=N'MG', @pCodigoIbge=31, @xDataHoraReg=default, @xLoginReg=default, @oPais_pId=1, @_trackLastWriteUser=@su
EXECUTE [dbo].[usuario_Save] @pId=1, @pCodigo=1, @pLogin=N'ADMIN', @pSenha=N'b', @pFlgAdmin=N'S', @sStatus=default, @xDataHoraReg=default, @xLoginReg=default, @oCadastro_pId=default, @oIdUser_Id=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[usuario_Savefilialousuarios] @pId=1, @pId2=1
EXECUTE [dbo].[usuario_Savefilialousuarios] @pId=2, @pId2=1
EXECUTE [dbo].[usuario_Save] @pId=2, @pCodigo=2, @pLogin=N'RENATO', @pSenha=N'r', @pFlgAdmin=N'N', @sStatus=default, @xDataHoraReg=default, @xLoginReg=default, @oCadastro_pId=1, @oIdUser_Id=default, @_trackLastWriteUser=@su
EXECUTE [dbo].[usuario_Savefilialousuarios] @pId=1, @pId2=2
EXECUTE [dbo].[usuario_Savefilialousuarios] @pId=2, @pId2=2
EXECUTE [dbo].[usuario_SaveapprelatoriooUsuarios] @pId=1, @pId2=2
EXECUTE [dbo].[usuario_SaveapprelatoriooUsuarios] @pId=2, @pId2=2
EXECUTE [dbo].[usuario_SaveapprelatoriooUsuarios] @pId=3, @pId2=2
EXECUTE [dbo].[usuario_SaveapprelatoriooUsuarios] @pId=4, @pId2=2
EXECUTE [dbo].[usuario_SaveapprelatoriooUsuarios] @pId=5, @pId2=2
EXECUTE [dbo].[usuario_SaveapprelatoriooUsuarios] @pId=6, @pId2=2
EXECUTE [dbo].[usuario_SaveapprelatoriooUsuarios] @pId=7, @pId2=2
EXECUTE [dbo].[WebSiteMap_Save] @pId=1, @pRelPath=N'~/frmUsina/cnEntCana/Cana/cnEntCanaEntradasCana.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Entrada de Cana', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=2, @pRelPath=N'~/frmUsina/cnEntCana/CanaPorOrigem/cnEntCanaEntradasCanaPorOrigem.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Entrada de Cana por Origem', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=3, @pRelPath=N'~/frmUsina/cnEntCana/CanaPorPropriedade/cnEntCanaEntradasCanaPorPropDualGeralFrente.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Entrada de Cana por Propriedade', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=4, @pRelPath=N'~/frmUsina/cnEntCana/CanaMapa/cnEntCanaEntradasCanaMapa.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Mapa de Entrada por Municipio', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=5, @pRelPath=N'~/frmUsina/cnEntCana/CanaMapaPropriedades/cnEntCanaEntradasCanaMapaPropriedades.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Mapa de Entrada por Propriedade', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=6, @pRelPath=N'~/frmUsina/cnEntCana/PivotEntradaCana/pivotEntradaCana.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Pivot Entrada de Cana', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=7, @pRelPath=N'~/frmUsina/cnEntCana/RelEntradasPropriedades/relEntradasPropriedades.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Relatorio Entradas por Propriedade', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=8, @pRelPath=N'~/frmUsina/cnEntCana/ColheitaCertificados/cnEntCanaColheitaCertificados.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Informacoes Gerais', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=9, @pRelPath=N'~/frmUsina/cnEntCana/PlanejamentoColheita/cnEntCanaPlanejamentoColheitaMapa.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Planejamento de Colheita', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=10, @pRelPath=N'~/frmUsina/cnEntCana/AcompProdutividade1Corte/cnEntCanaAcompProdutividade1Corte.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Acomp  Produtividade 1o Corte', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=11, @pRelPath=N'~/frmUsina/cnEntCana/AcompProdutividadeDCorte/cnEntCanaAcompProdutividadeDCorte.aspx', @pNode=N'Cenario Colheita de Cana', @pDescription=N'Acomp  Produtividade Demais Cortes', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=12, @pRelPath=N'~/frmUsina/cnOficina/Resumo/cnOficinaResumoDualGeralFrente.aspx', @pNode=N'Cenario Oficina Automotiva', @pDescription=N'Resumo Oficina', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=13, @pRelPath=N'~/frmUsina/cnOficina/Detalhamento/cnOficinaDetalhamentoTriGeralCmFr.aspx', @pNode=N'Cenario Oficina Automotiva', @pDescription=N'Detalhamento Oficina', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=14, @pRelPath=N'~/frmUsina/cnOficina/ResumoEquip/cnOficinaResumoEquipamentos.aspx', @pNode=N'Cenario Oficina Automotiva', @pDescription=N'Resumo dos Equipamentos na Oficina', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=15, @pRelPath=N'~/frmUsina/cnEntCanaMob/EntradaCanaHora/cnEntCanaMobEntradasCanaHoraDualGeralFrente.aspx', @pNode=N'Cenario Entrada Cana Mobile', @pDescription=N'Entrada de Cana Hora', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=16, @pRelPath=N'~/frmUsina/cnEntCanaMob/MoagemCanaHora/cnEntCanaMobMoagemCanaHora.aspx', @pNode=N'Cenario Entrada Cana Mobile', @pDescription=N'Moagem de Cana Hora', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=17, @pRelPath=N'~/frmUsina/cnEntCanaMob/CertificadoHora/cnEntCanaMobEntradasCertificadoHora.aspx', @pNode=N'Cenario Entrada Cana Mobile', @pDescription=N'Certificado de Cana Hora', @_trackLastWriteUser=@su
EXECUTE [dbo].[WebSiteMap_Save] @pId=18, @pRelPath=N'~/frmUsina/cnAcesso/LogAcessoBI/LogAcessos.aspx', @pNode=N'Acesso', @pDescription=N'Log de Acesso ao BI', @_trackLastWriteUser=@su
