'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace S5TUam
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: .
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute(),  _
     System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, DSC_PROPRIEDADE={DSC_PROPRIEDADE}, pId={pId}"),  _
     System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.NameTypeConverter))>  _
    Partial Public Class INFO_GERAIS
        Implements System.ICloneable, System.IComparable, System.IComparable(Of S5TUam.INFO_GERAIS), CodeFluent.Runtime.ICodeFluentCollectionEntity(Of Long), System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable(Of S5TUam.INFO_GERAIS)
        
        Private _raisePropertyChangedEvents As Boolean = true
        
        Private _entityState As CodeFluent.Runtime.CodeFluentEntityState
        
        Private _pId As Long = -1
        
        Private _fRENTE As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _pROPRIEDADE As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _dSC_PROPRIEDADE As String = CType(Nothing, String)
        
        Private _cOLHEDORA As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _tONELADA As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _qTD_VIAGENS As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _mEDIA_VIAGEM As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _rAIO_MEDIO As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_MINERAL As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_VEGETAL_PALHA As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_VEGETAL_PONTEIRA As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_MINERAL1 As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_MINERAL2 As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_VEGETAL_PALHA1 As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_VEGETAL_PALHA2 As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_VEGETAL_PONTEIRA1 As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _iMP_VEGETAL_PONTEIRA2 As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Public Sub New()
            MyBase.New
            Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Overridable Property RaisePropertyChangedEvents() As Boolean
            Get
                Return Me._raisePropertyChangedEvents
            End Get
            Set
                Me._raisePropertyChangedEvents = value
            End Set
        End Property
        
        Public Overridable Property EntityKey() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityKey
            Get
                Return Me.pId.ToString
            End Get
            Set
                Me.pId = CType(ConvertUtilities.ChangeType(value, GetType(Long), -1),Long)
            End Set
        End Property
        
        Public Overridable ReadOnly Property EntityDisplayName() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityDisplayName
            Get
                Return Me.DSC_PROPRIEDADE
            End Get
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(-1,Long)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Long)),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property pId() As Long
            Get
                Return Me._pId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Long).Default.Equals(value, Me._pId) = true) Then
                    Return
                End If
                Dim oldKey As Long = Me._pId
                Me._pId = value
                Try 
                    Me.OnCollectionKeyChanged(oldKey)
                Catch __exception As System.ArgumentException
                    Me._pId = oldKey
                    Return
                End Try
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pId"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property FRENTE() As Integer
            Get
                Return Me._fRENTE
            End Get
            Set
                Me._fRENTE = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("FRENTE"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property PROPRIEDADE() As Integer
            Get
                Return Me._pROPRIEDADE
            End Get
            Set
                Me._pROPRIEDADE = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("PROPRIEDADE"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property DSC_PROPRIEDADE() As String
            Get
                Return Me._dSC_PROPRIEDADE
            End Get
            Set
                Me._dSC_PROPRIEDADE = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("DSC_PROPRIEDADE"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property COLHEDORA() As Integer
            Get
                Return Me._cOLHEDORA
            End Get
            Set
                Me._cOLHEDORA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("COLHEDORA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property TONELADA() As Double
            Get
                Return Me._tONELADA
            End Get
            Set
                Me._tONELADA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("TONELADA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property QTD_VIAGENS() As Integer
            Get
                Return Me._qTD_VIAGENS
            End Get
            Set
                Me._qTD_VIAGENS = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("QTD_VIAGENS"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property MEDIA_VIAGEM() As Double
            Get
                Return Me._mEDIA_VIAGEM
            End Get
            Set
                Me._mEDIA_VIAGEM = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("MEDIA_VIAGEM"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property RAIO_MEDIO() As Double
            Get
                Return Me._rAIO_MEDIO
            End Get
            Set
                Me._rAIO_MEDIO = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("RAIO_MEDIO"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_MINERAL() As Double
            Get
                Return Me._iMP_MINERAL
            End Get
            Set
                Me._iMP_MINERAL = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_MINERAL"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_VEGETAL_PALHA() As Double
            Get
                Return Me._iMP_VEGETAL_PALHA
            End Get
            Set
                Me._iMP_VEGETAL_PALHA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_VEGETAL_PALHA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_VEGETAL_PONTEIRA() As Double
            Get
                Return Me._iMP_VEGETAL_PONTEIRA
            End Get
            Set
                Me._iMP_VEGETAL_PONTEIRA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_VEGETAL_PONTEIRA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_MINERAL1() As Double
            Get
                Return Me._iMP_MINERAL1
            End Get
            Set
                Me._iMP_MINERAL1 = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_MINERAL1"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_MINERAL2() As Double
            Get
                Return Me._iMP_MINERAL2
            End Get
            Set
                Me._iMP_MINERAL2 = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_MINERAL2"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_VEGETAL_PALHA1() As Double
            Get
                Return Me._iMP_VEGETAL_PALHA1
            End Get
            Set
                Me._iMP_VEGETAL_PALHA1 = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_VEGETAL_PALHA1"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_VEGETAL_PALHA2() As Double
            Get
                Return Me._iMP_VEGETAL_PALHA2
            End Get
            Set
                Me._iMP_VEGETAL_PALHA2 = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_VEGETAL_PALHA2"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_VEGETAL_PONTEIRA1() As Double
            Get
                Return Me._iMP_VEGETAL_PONTEIRA1
            End Get
            Set
                Me._iMP_VEGETAL_PONTEIRA1 = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_VEGETAL_PONTEIRA1"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property IMP_VEGETAL_PONTEIRA2() As Double
            Get
                Return Me._iMP_VEGETAL_PONTEIRA2
            End Get
            Set
                Me._iMP_VEGETAL_PONTEIRA2 = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IMP_VEGETAL_PONTEIRA2"))
            End Set
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Error() As String Implements System.ComponentModel.IDataErrorInfo.[Error]
            Get
                Return Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            End Get
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Item(ByVal columnName As String) As String Implements System.ComponentModel.IDataErrorInfo.Item
            Get
                Return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, Me, columnName, Nothing)
            End Get
        End Property
        
        ReadOnly Property CodeFluent_Runtime_Utilities_IKeyable_System_Int64__Key() As Long Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).Key
            Get
                Return Me.pId
            End Get
        End Property
        
        Public Overridable Property EntityState() As CodeFluent.Runtime.CodeFluentEntityState Implements CodeFluent.Runtime.ICodeFluentEntity.EntityState
            Get
                Return Me._entityState
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of CodeFluent.Runtime.CodeFluentEntityState).Default.Equals(value, Me.EntityState) = true) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                Me._entityState = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("EntityState"))
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Public Event EntityAction As CodeFluent.Runtime.CodeFluentEntityActionEventHandler Implements CodeFluent.Runtime.ICodeFluentEntity.EntityAction
        
        Public Event KeyChanged As System.EventHandler(Of CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)) Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).KeyChanged
        
        Protected Overridable Sub OnPropertyChanged(ByVal e As System.ComponentModel.PropertyChangedEventArgs)
            If (Me.RaisePropertyChangedEvents = false) Then
                Return
            End If
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, e)
            End If
        End Sub
        
        Protected Overridable Sub OnEntityAction(ByVal e As CodeFluent.Runtime.CodeFluentEntityActionEventArgs)
            If (Not (Me.EntityActionEvent) Is Nothing) Then
                RaiseEvent EntityAction(Me, e)
            End If
        End Sub
        
        Public Overloads Overridable Function Equals(ByVal iNFO_GERAIS As S5TUam.INFO_GERAIS) As Boolean Implements System.IEquatable(Of S5TUam.INFO_GERAIS).Equals
            If (iNFO_GERAIS Is Nothing) Then
                Return false
            End If
            If (Me.pId = -1) Then
                Return MyBase.Equals(iNFO_GERAIS)
            End If
            Return (Me.pId.Equals(iNFO_GERAIS.pId) = true)
        End Function
        
        Public Overloads Overrides Function GetHashCode() As Integer
            Return Me.pId.GetHashCode
        End Function
        
        Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
            Dim iNFO_GERAIS As S5TUam.INFO_GERAIS = Nothing
            Try 
                iNFO_GERAIS = CType(obj,S5TUam.INFO_GERAIS)
            Catch icex As System.InvalidCastException
                iNFO_GERAIS = Nothing
            End Try
            Return Me.Equals(iNFO_GERAIS)
        End Function
        
        Overridable Function System_IComparable_CompareTo(ByVal value As Object) As Integer Implements System.IComparable.CompareTo
            Dim iNFO_GERAIS As S5TUam.INFO_GERAIS = Nothing
            Try 
                iNFO_GERAIS = CType(value,S5TUam.INFO_GERAIS)
            Catch icex As System.InvalidCastException
                iNFO_GERAIS = Nothing
            End Try
            If (iNFO_GERAIS Is Nothing) Then
                Throw New System.ArgumentException("value")
            End If
            Dim localCompareTo As Integer = Me.CompareTo(iNFO_GERAIS)
            Return localCompareTo
        End Function
        
        Public Overridable Function CompareTo(ByVal iNFO_GERAIS As S5TUam.INFO_GERAIS) As Integer Implements System.IComparable(Of S5TUam.INFO_GERAIS).CompareTo
            If (iNFO_GERAIS Is Nothing) Then
                Throw New System.ArgumentNullException("iNFO_GERAIS")
            End If
            Dim localCompareTo As Integer = Me.pId.CompareTo(iNFO_GERAIS.pId)
            Return localCompareTo
        End Function
        
        Public Overloads Overridable Function Validate(ByVal culture As System.Globalization.CultureInfo) As String
            Return CodeFluentPersistence.Validate(culture, Me, Nothing)
        End Function
        
        Public Overloads Overridable Sub Validate(ByVal culture As System.Globalization.CultureInfo, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentSummaryValidator.Validate
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results)
            evt.Culture = culture
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Dim externalValidate As String
                If (Not (evt.Argument) Is Nothing) Then
                    externalValidate = evt.Argument.ToString
                Else
                    externalValidate = S5T.Resources.Manager.GetStringWithDefault(culture, "S5TUam.INFO_GERAIS.ExternalValidate", "Type 'S5TUam.INFO_GERAIS' cannot be validated.", Nothing)
                End If
                CodeFluentPersistence.AddValidationError(results, externalValidate)
            End If
            CodeFluentPersistence.ValidateMember(culture, results, Me, Nothing)
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results))
        End Sub
        
        Public Overloads Sub Validate()
            Dim var As String = Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            If (Not (var) Is Nothing) Then
                Throw New CodeFluent.Runtime.CodeFluentValidationException(var)
            End If
        End Sub
        
        Function CodeFluent_Runtime_ICodeFluentValidator_Validate(ByVal culture As System.Globalization.CultureInfo) As String Implements CodeFluent.Runtime.ICodeFluentValidator.Validate
            Dim localValidate As String = Me.Validate(culture)
            Return localValidate
        End Function
        
        Sub CodeFluent_Runtime_ICodeFluentMemberValidator_Validate(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentMemberValidator.Validate
            Me.ValidateMember(culture, memberName, results)
        End Sub
        
        Public Overloads Overridable Function Delete() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Delete
            Dim ret As Boolean = false
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return ret
            End If
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "INFO_GERAIS", "Delete")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.ExecuteNonQuery
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false))
            ret = true
            Return ret
        End Function
        
        Protected Overridable Sub ReadRecord(ByVal reader As System.Data.IDataReader, ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.Properties)  _
                        = 0)  _
                        = false) Then
                Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
                Me._fRENTE = CodeFluentPersistence.GetReaderValue(reader, "FRENTE", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._pROPRIEDADE = CodeFluentPersistence.GetReaderValue(reader, "PROPRIEDADE", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._dSC_PROPRIEDADE = CodeFluentPersistence.GetReaderValue(reader, "DSC_PROPRIEDADE", CType(CType(Nothing, String),String))
                Me._cOLHEDORA = CodeFluentPersistence.GetReaderValue(reader, "COLHEDORA", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._tONELADA = CodeFluentPersistence.GetReaderValue(reader, "TONELADA", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._qTD_VIAGENS = CodeFluentPersistence.GetReaderValue(reader, "QTD_VIAGENS", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._mEDIA_VIAGEM = CodeFluentPersistence.GetReaderValue(reader, "MEDIA_VIAGEM", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._rAIO_MEDIO = CodeFluentPersistence.GetReaderValue(reader, "RAIO_MEDIO", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_MINERAL = CodeFluentPersistence.GetReaderValue(reader, "IMP_MINERAL", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_VEGETAL_PALHA = CodeFluentPersistence.GetReaderValue(reader, "IMP_VEGETAL_PALHA", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_VEGETAL_PONTEIRA = CodeFluentPersistence.GetReaderValue(reader, "IMP_VEGETAL_PONTEIRA", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_MINERAL1 = CodeFluentPersistence.GetReaderValue(reader, "IMP_MINERAL1", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_MINERAL2 = CodeFluentPersistence.GetReaderValue(reader, "IMP_MINERAL2", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_VEGETAL_PALHA1 = CodeFluentPersistence.GetReaderValue(reader, "IMP_VEGETAL_PALHA1", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_VEGETAL_PALHA2 = CodeFluentPersistence.GetReaderValue(reader, "IMP_VEGETAL_PALHA2", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_VEGETAL_PONTEIRA1 = CodeFluentPersistence.GetReaderValue(reader, "IMP_VEGETAL_PONTEIRA1", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._iMP_VEGETAL_PONTEIRA2 = CodeFluentPersistence.GetReaderValue(reader, "IMP_VEGETAL_PONTEIRA2", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecord(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecord
            Me.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
        End Sub
        
        Protected Overridable Sub ReadRecordOnSave(ByVal reader As System.Data.IDataReader)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecordOnSave(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave
            Me.ReadRecordOnSave(reader)
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function Load(ByVal pId As Long) As S5TUam.INFO_GERAIS
            If (pId = -1) Then
                Return Nothing
            End If
            Dim iNFO_GERAIS As S5TUam.INFO_GERAIS = New S5TUam.INFO_GERAIS()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "INFO_GERAIS", "Load")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    iNFO_GERAIS.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    iNFO_GERAIS.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return iNFO_GERAIS
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], false)>  _
        Public Shared Function LoadBypId(ByVal pId As Long) As S5TUam.INFO_GERAIS
            If (pId = -1) Then
                Return Nothing
            End If
            Dim iNFO_GERAIS As S5TUam.INFO_GERAIS = New S5TUam.INFO_GERAIS()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "INFO_GERAIS", "LoadBypId")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    iNFO_GERAIS.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    iNFO_GERAIS.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return iNFO_GERAIS
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        Public Overridable Function Reload(ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions) As Boolean
            Dim ret As Boolean = false
            If (Me.pId = -1) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "INFO_GERAIS", "Load")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecord(reader, options)
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    ret = true
                Else
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return ret
        End Function
        
        Protected Overridable Function BaseSave(ByVal force As Boolean) As Boolean
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) Then
                S5TUam.INFO_GERAIS.Delete(Me)
                Return false
            End If
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return false
            End If
            CodeFluentPersistence.ThrowIfDeleted(Me)
            Me.Validate
            If ((force = false)  _
                        AndAlso (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged)) Then
                Return false
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "INFO_GERAIS", "Save")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.AddParameter("@FRENTE", Me.FRENTE, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@PROPRIEDADE", Me.PROPRIEDADE, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@DSC_PROPRIEDADE", Me.DSC_PROPRIEDADE, CType(Nothing, String))
            persistence.AddParameter("@COLHEDORA", Me.COLHEDORA, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@TONELADA", Me.TONELADA, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@QTD_VIAGENS", Me.QTD_VIAGENS, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@MEDIA_VIAGEM", Me.MEDIA_VIAGEM, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@RAIO_MEDIO", Me.RAIO_MEDIO, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_MINERAL", Me.IMP_MINERAL, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_VEGETAL_PALHA", Me.IMP_VEGETAL_PALHA, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_VEGETAL_PONTEIRA", Me.IMP_VEGETAL_PONTEIRA, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_MINERAL1", Me.IMP_MINERAL1, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_MINERAL2", Me.IMP_MINERAL2, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_VEGETAL_PALHA1", Me.IMP_VEGETAL_PALHA1, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_VEGETAL_PALHA2", Me.IMP_VEGETAL_PALHA2, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_VEGETAL_PONTEIRA1", Me.IMP_VEGETAL_PONTEIRA1, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@IMP_VEGETAL_PONTEIRA2", Me.IMP_VEGETAL_PONTEIRA2, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@_trackLastWriteUser", persistence.Context.User.Name)
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecordOnSave(reader)
                End If
                CodeFluentPersistence.NextResults(reader)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false))
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
            Return true
        End Function
        
        Public Overloads Overridable Function Save() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Save
            Dim localSave As Boolean = Me.BaseSave(false)
            Return localSave
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Shared Function Save(ByVal iNFO_GERAIS As S5TUam.INFO_GERAIS) As Boolean
            If (iNFO_GERAIS Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = iNFO_GERAIS.Save
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Shared Function Insert(ByVal iNFO_GERAIS As S5TUam.INFO_GERAIS) As Boolean
            Dim ret As Boolean = S5TUam.INFO_GERAIS.Save(iNFO_GERAIS)
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Shared Function Delete(ByVal iNFO_GERAIS As S5TUam.INFO_GERAIS) As Boolean
            If (iNFO_GERAIS Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = iNFO_GERAIS.Delete
            Return ret
        End Function
        
        Public Function Trace() As String
            Dim stringBuilder As System.Text.StringBuilder = New System.Text.StringBuilder()
            Dim stringWriter As System.IO.StringWriter = New System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture)
            Dim writer As System.CodeDom.Compiler.IndentedTextWriter = New System.CodeDom.Compiler.IndentedTextWriter(stringWriter)
            Me.BaseTrace(writer)
            writer.Flush
            CType(writer,System.IDisposable).Dispose
            CType(stringWriter,System.IDisposable).Dispose
            Dim sr As String = stringBuilder.ToString
            Return sr
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub CodeFluent_Runtime_ICodeFluentObject_Trace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter) Implements CodeFluent.Runtime.ICodeFluentObject.Trace
            Me.BaseTrace(writer)
        End Sub
        
        Protected Overridable Sub BaseTrace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter)
            writer.Write("[")
            writer.Write("pId=")
            writer.Write(Me.pId)
            writer.Write(",")
            writer.Write("FRENTE=")
            writer.Write(Me.FRENTE)
            writer.Write(",")
            writer.Write("PROPRIEDADE=")
            writer.Write(Me.PROPRIEDADE)
            writer.Write(",")
            writer.Write("DSC_PROPRIEDADE=")
            writer.Write(Me.DSC_PROPRIEDADE)
            writer.Write(",")
            writer.Write("COLHEDORA=")
            writer.Write(Me.COLHEDORA)
            writer.Write(",")
            writer.Write("TONELADA=")
            writer.Write(Me.TONELADA)
            writer.Write(",")
            writer.Write("QTD_VIAGENS=")
            writer.Write(Me.QTD_VIAGENS)
            writer.Write(",")
            writer.Write("MEDIA_VIAGEM=")
            writer.Write(Me.MEDIA_VIAGEM)
            writer.Write(",")
            writer.Write("RAIO_MEDIO=")
            writer.Write(Me.RAIO_MEDIO)
            writer.Write(",")
            writer.Write("IMP_MINERAL=")
            writer.Write(Me.IMP_MINERAL)
            writer.Write(",")
            writer.Write("IMP_VEGETAL_PALHA=")
            writer.Write(Me.IMP_VEGETAL_PALHA)
            writer.Write(",")
            writer.Write("IMP_VEGETAL_PONTEIRA=")
            writer.Write(Me.IMP_VEGETAL_PONTEIRA)
            writer.Write(",")
            writer.Write("IMP_MINERAL1=")
            writer.Write(Me.IMP_MINERAL1)
            writer.Write(",")
            writer.Write("IMP_MINERAL2=")
            writer.Write(Me.IMP_MINERAL2)
            writer.Write(",")
            writer.Write("IMP_VEGETAL_PALHA1=")
            writer.Write(Me.IMP_VEGETAL_PALHA1)
            writer.Write(",")
            writer.Write("IMP_VEGETAL_PALHA2=")
            writer.Write(Me.IMP_VEGETAL_PALHA2)
            writer.Write(",")
            writer.Write("IMP_VEGETAL_PONTEIRA1=")
            writer.Write(Me.IMP_VEGETAL_PONTEIRA1)
            writer.Write(",")
            writer.Write("IMP_VEGETAL_PONTEIRA2=")
            writer.Write(Me.IMP_VEGETAL_PONTEIRA2)
            writer.Write(", EntityState=")
            writer.Write(Me.EntityState)
            writer.Write("]")
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function LoadByEntityKey(ByVal key As String) As S5TUam.INFO_GERAIS
            If (key Is String.Empty) Then
                Return Nothing
            End If
            Dim iNFO_GERAIS As S5TUam.INFO_GERAIS
            Dim var As Long = CType(ConvertUtilities.ChangeType(key, GetType(Long), -1),Long)
            iNFO_GERAIS = S5TUam.INFO_GERAIS.Load(var)
            Return iNFO_GERAIS
        End Function
        
        Protected Overridable Sub ValidateMember(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException))
        End Sub
        
        Public Overloads Function Clone(ByVal deep As Boolean) As S5TUam.INFO_GERAIS
            Dim iNFO_GERAIS As S5TUam.INFO_GERAIS = New S5TUam.INFO_GERAIS()
            Me.CopyTo(iNFO_GERAIS, deep)
            Return iNFO_GERAIS
        End Function
        
        Public Overloads Function Clone() As S5TUam.INFO_GERAIS
            Dim localClone As S5TUam.INFO_GERAIS = Me.Clone(true)
            Return localClone
        End Function
        
        Function System_ICloneable_Clone() As Object Implements System.ICloneable.Clone
            Dim localClone As Object = Me.Clone
            Return localClone
        End Function
        
        Public Overridable Sub CopyFrom(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            If (dict.Contains("pId") = true) Then
                Me.pId = CType(ConvertUtilities.ChangeType(dict("pId"), GetType(Long), -1),Long)
            End If
            If (dict.Contains("IMP_MINERAL1") = true) Then
                Me.IMP_MINERAL1 = CType(ConvertUtilities.ChangeType(dict("IMP_MINERAL1"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("IMP_MINERAL2") = true) Then
                Me.IMP_MINERAL2 = CType(ConvertUtilities.ChangeType(dict("IMP_MINERAL2"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("IMP_VEGETAL_PALHA") = true) Then
                Me.IMP_VEGETAL_PALHA = CType(ConvertUtilities.ChangeType(dict("IMP_VEGETAL_PALHA"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("IMP_VEGETAL_PONTEIRA") = true) Then
                Me.IMP_VEGETAL_PONTEIRA = CType(ConvertUtilities.ChangeType(dict("IMP_VEGETAL_PONTEIRA"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("IMP_VEGETAL_PONTEIRA1") = true) Then
                Me.IMP_VEGETAL_PONTEIRA1 = CType(ConvertUtilities.ChangeType(dict("IMP_VEGETAL_PONTEIRA1"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("IMP_VEGETAL_PONTEIRA2") = true) Then
                Me.IMP_VEGETAL_PONTEIRA2 = CType(ConvertUtilities.ChangeType(dict("IMP_VEGETAL_PONTEIRA2"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("IMP_VEGETAL_PALHA1") = true) Then
                Me.IMP_VEGETAL_PALHA1 = CType(ConvertUtilities.ChangeType(dict("IMP_VEGETAL_PALHA1"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("IMP_VEGETAL_PALHA2") = true) Then
                Me.IMP_VEGETAL_PALHA2 = CType(ConvertUtilities.ChangeType(dict("IMP_VEGETAL_PALHA2"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("IMP_MINERAL") = true) Then
                Me.IMP_MINERAL = CType(ConvertUtilities.ChangeType(dict("IMP_MINERAL"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("DSC_PROPRIEDADE") = true) Then
                Me.DSC_PROPRIEDADE = CType(ConvertUtilities.ChangeType(dict("DSC_PROPRIEDADE"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("COLHEDORA") = true) Then
                Me.COLHEDORA = CType(ConvertUtilities.ChangeType(dict("COLHEDORA"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("FRENTE") = true) Then
                Me.FRENTE = CType(ConvertUtilities.ChangeType(dict("FRENTE"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("PROPRIEDADE") = true) Then
                Me.PROPRIEDADE = CType(ConvertUtilities.ChangeType(dict("PROPRIEDADE"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("MEDIA_VIAGEM") = true) Then
                Me.MEDIA_VIAGEM = CType(ConvertUtilities.ChangeType(dict("MEDIA_VIAGEM"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("RAIO_MEDIO") = true) Then
                Me.RAIO_MEDIO = CType(ConvertUtilities.ChangeType(dict("RAIO_MEDIO"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("TONELADA") = true) Then
                Me.TONELADA = CType(ConvertUtilities.ChangeType(dict("TONELADA"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("QTD_VIAGENS") = true) Then
                Me.QTD_VIAGENS = CType(ConvertUtilities.ChangeType(dict("QTD_VIAGENS"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal iNFO_GERAIS As S5TUam.INFO_GERAIS, ByVal deep As Boolean)
            If (iNFO_GERAIS Is Nothing) Then
                Throw New System.ArgumentNullException("iNFO_GERAIS")
            End If
            iNFO_GERAIS.pId = Me.pId
            iNFO_GERAIS.IMP_MINERAL1 = Me.IMP_MINERAL1
            iNFO_GERAIS.IMP_MINERAL2 = Me.IMP_MINERAL2
            iNFO_GERAIS.IMP_VEGETAL_PALHA = Me.IMP_VEGETAL_PALHA
            iNFO_GERAIS.IMP_VEGETAL_PONTEIRA = Me.IMP_VEGETAL_PONTEIRA
            iNFO_GERAIS.IMP_VEGETAL_PONTEIRA1 = Me.IMP_VEGETAL_PONTEIRA1
            iNFO_GERAIS.IMP_VEGETAL_PONTEIRA2 = Me.IMP_VEGETAL_PONTEIRA2
            iNFO_GERAIS.IMP_VEGETAL_PALHA1 = Me.IMP_VEGETAL_PALHA1
            iNFO_GERAIS.IMP_VEGETAL_PALHA2 = Me.IMP_VEGETAL_PALHA2
            iNFO_GERAIS.IMP_MINERAL = Me.IMP_MINERAL
            iNFO_GERAIS.DSC_PROPRIEDADE = Me.DSC_PROPRIEDADE
            iNFO_GERAIS.COLHEDORA = Me.COLHEDORA
            iNFO_GERAIS.FRENTE = Me.FRENTE
            iNFO_GERAIS.PROPRIEDADE = Me.PROPRIEDADE
            iNFO_GERAIS.MEDIA_VIAGEM = Me.MEDIA_VIAGEM
            iNFO_GERAIS.RAIO_MEDIO = Me.RAIO_MEDIO
            iNFO_GERAIS.TONELADA = Me.TONELADA
            iNFO_GERAIS.QTD_VIAGENS = Me.QTD_VIAGENS
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, iNFO_GERAIS))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            dict("pId") = Me.pId
            dict("IMP_MINERAL1") = Me.IMP_MINERAL1
            dict("IMP_MINERAL2") = Me.IMP_MINERAL2
            dict("IMP_VEGETAL_PALHA") = Me.IMP_VEGETAL_PALHA
            dict("IMP_VEGETAL_PONTEIRA") = Me.IMP_VEGETAL_PONTEIRA
            dict("IMP_VEGETAL_PONTEIRA1") = Me.IMP_VEGETAL_PONTEIRA1
            dict("IMP_VEGETAL_PONTEIRA2") = Me.IMP_VEGETAL_PONTEIRA2
            dict("IMP_VEGETAL_PALHA1") = Me.IMP_VEGETAL_PALHA1
            dict("IMP_VEGETAL_PALHA2") = Me.IMP_VEGETAL_PALHA2
            dict("IMP_MINERAL") = Me.IMP_MINERAL
            dict("DSC_PROPRIEDADE") = Me.DSC_PROPRIEDADE
            dict("COLHEDORA") = Me.COLHEDORA
            dict("FRENTE") = Me.FRENTE
            dict("PROPRIEDADE") = Me.PROPRIEDADE
            dict("MEDIA_VIAGEM") = Me.MEDIA_VIAGEM
            dict("RAIO_MEDIO") = Me.RAIO_MEDIO
            dict("TONELADA") = Me.TONELADA
            dict("QTD_VIAGENS") = Me.QTD_VIAGENS
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict))
        End Sub
        
        Protected Sub OnCollectionKeyChanged(ByVal key As Long)
            If (Not (Me.KeyChangedEvent) Is Nothing) Then
                RaiseEvent KeyChanged(Me, New CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)(key))
            End If
        End Sub
    End Class
End Namespace
